export interface QuizQuestion {
  q: string;
  options: string[];
  correctAnswer: number;
  explanation?: string;
}

export type ActivityType =
  | "password-strength"
  | "compare-emails"
  | "fake-screenshots"
  | "permissions-review"
  | "profile-privacy";

export interface ActivityData {
  type: ActivityType;
  title: string;
  instructions: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  data: any;
}

export interface Lesson {
  id: string;
  title: string;
  summary: string;
  readTime: string;
  difficulty: "Beginner" | "Intermediate";
  explanation: string;
  illustration: string; // ASCII Visual
  takeaways: string[];
  activity: ActivityData;
  quiz: QuizQuestion[];
}

export interface CaseStudy {
  title: string;
  background: string;
  story: string;
  timeline: string[];
  mistakes: string[];
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  lessonsLearned: string[];
}

export interface Unit {
  id: string;
  title: string;
  difficulty: "Beginner" | "Intermediate";
  estimatedTime: string;
  lessons: Lesson[];
  caseStudy: CaseStudy;
}

export const CURRICULUM: Unit[] = [
  {
    id: "unit-1",
    title: "Digital Safety Basics",
    difficulty: "Beginner",
    estimatedTime: "15 min",
    lessons: [
      {
        id: "lesson-1-1",
        title: "Creating Strong Passwords",
        summary: "Learn why longer passwords made of simple words are much safer than short complex ones.",
        readTime: "3 min read",
        difficulty: "Beginner",
        explanation: "Hacking tools guess passwords by running through common words and combinations at incredible speed. A password like 'P@ssw0rd!' seems complex but is short, making it easy to guess. Instead, combining four random common words (like 'apple-chair-river-sunset') creates a much longer password that is easy for you to remember but takes a computer trillions of years to guess.",
        illustration: `+-------------------------------------------------------------+
| HOW HACKING TOOLS GUESS PASSWORDS (SPEED COMPARISON)        |
|                                                             |
| "P@ssw0rd!" (8 Chars)       ====> Guessed Instantly         |
| "Tr0ub14!" (8 Chars)        ====> Guessed in 2 Seconds      |
| "apple-chair-river-sunset"  ====> Takes Trillions of Years  |
+-------------------------------------------------------------+`,
        takeaways: [
          "Password length is much more important than using weird symbols.",
          "Use a combination of 4 or more random words (a passphrase).",
          "Never reuse the same password across multiple websites."
        ],
        activity: {
          type: "password-strength",
          title: "Test Your Password Strength",
          instructions: "Type different passwords below to see how long it takes a computer to guess them. Try making a passphrase with simple words!",
          data: {}
        },
        quiz: [
          {
            q: "Why is 'correct-horse-battery-staple' a better password than 'Tr0ub14!'?",
            options: [
              "Because it uses more special characters.",
              "Because it is much longer, making it harder for computers to guess.",
              "Because it is written in all lowercase letters.",
              "Because it doesn't contain any dictionary words."
            ],
            correctAnswer: 1,
            explanation: "Length is the most critical factor in password strength. A passphrase made of several random words is long and extremely secure, yet easy to remember."
          },
          {
            q: "What is the danger of using the same password on multiple websites?",
            options: [
              "Your password will be too long to type.",
              "The browser will log you out automatically.",
              "If one small website gets hacked, scammers can log into all your other accounts.",
              "It slows down your internet connection."
            ],
            correctAnswer: 2,
            explanation: "Scammers use databases of leaked passwords from hacked sites to log into popular services. Having a unique password for each site isolates the risk."
          }
        ]
      },
      {
        id: "lesson-1-2",
        title: "Adding a Second Lock (MFA)",
        summary: "Understand Multi-Factor Authentication (MFA) and why it blocks hackers even if they know your password.",
        readTime: "4 min read",
        difficulty: "Beginner",
        explanation: "Multi-Factor Authentication (MFA) adds a second lock to your accounts. Instead of just a password, you need something else—like a verification code sent to your phone or generated by an app. Even if a scammer steals your password, they cannot access your account without that second code.",
        illustration: `+-------------------------------------------------------------+
| HOW MFA PROTECTS YOUR ACCOUNT                               |
|                                                             |
| 1. Type Password  ===>  2. Enter Code from Phone  ===> Login |
|          ^                         ^                        |
|   Scammer knows this!     Scammer doesn't have this!         |
+-------------------------------------------------------------+`,
        takeaways: [
          "Enable MFA on all important accounts, especially email and banking.",
          "Authenticator apps (like Google Authenticator) are safer than SMS codes.",
          "Never share a verification code or One-Time Password (OTP) with anyone."
        ],
        activity: {
          type: "permissions-review",
          title: "Simulator: Set Up MFA",
          instructions: "Review the login permissions. Select the safest way to secure your login from the options.",
          data: {
            scenario: "mfa",
            options: [
              { id: "sms", label: "SMS Code MFA", desc: "Codes sent via SMS text message. Better than nothing, but can be hijacked.", rating: "Good" },
              { id: "app", label: "Authenticator App MFA", desc: "Codes generated on your device. Highly secure and offline.", rating: "Excellent" },
              { id: "none", label: "Password Only (No MFA)", desc: "Relies only on your password. Vulnerable to theft.", rating: "Risky" }
            ]
          }
        },
        quiz: [
          {
            q: "What does Multi-Factor Authentication (MFA) do?",
            options: [
              "It allows you to use multiple passwords for one account.",
              "It requires a second verification step, like a code from your phone, to log in.",
              "It automatically changes your password every week.",
              "It speeds up website loading times."
            ],
            correctAnswer: 1,
            explanation: "MFA requires two or more pieces of evidence to log in, making it much harder for scammers to hack your account."
          }
        ]
      },
      {
        id: "lesson-1-3",
        title: "Using a Password Manager",
        summary: "Learn how to use a digital vault to store and generate all your passwords securely.",
        readTime: "3 min read",
        difficulty: "Beginner",
        explanation: "Remembering dozens of unique, strong passwords is nearly impossible. A password manager acts as a secure digital notebook. It creates long, random passwords for each of your accounts and stores them behind one master password that only you know. It also fills them in automatically, saving you from typing them.",
        illustration: `+-------------------------------------------------------------+
| PASSWORD MANAGER SYSTEM                                     |
|                                                             |
| [Master Password] ===> [Your Digital Vault]                 |
|                              |                              |
|       +--- Generates and autofills secure keys:             |
|            * email: kf8#4dJ9!sPq                            |
|            * bank:  8d$mLaq29#zX                            |
+-------------------------------------------------------------+`,
        takeaways: [
          "A password manager generates and remembers passwords for you.",
          "You only need to remember one strong master passphrase.",
          "Use reputable managers like Bitwarden or 1Password."
        ],
        activity: {
          type: "profile-privacy",
          title: "Generate a Strong Password",
          instructions: "Configure the settings below to generate a secure, random password. Notice how adding more characters increases guess complexity!",
          data: {
            scenario: "generator"
          }
        },
        quiz: [
          {
            q: "What is the main benefit of a password manager?",
            options: [
              "It lets you write passwords on paper.",
              "It stores and generates unique, strong passwords so you don't have to remember them.",
              "It sends your passwords to the police for safekeeping.",
              "It encrypts your internet connection on public Wi-Fi."
            ],
            correctAnswer: 1,
            explanation: "Password managers eliminate the need to remember many passwords, allowing you to use complex, unique passwords for every site."
          }
        ]
      }
    ],
    caseStudy: {
      title: "The Fake Internship Scam",
      background: "Rahul, a first-year college student, was looking for a remote software internship online.",
      story: "Rahul received an email that looked exactly like it came from a major tech company. The email claimed he was selected for an internship and asked him to click a link to log in and sign his contract. Excited, Rahul clicked the link, which took him to a page that looked like his college login portal. He entered his username and password. The page showed an error, and nothing happened. The next day, Rahul was locked out of his college email and student portal, and scam emails were sent to all his professors from his account.",
      timeline: [
        "Rahul posts his resume on an open job forum.",
        "Scammer sends a spoofed email offering a 'direct selection' internship.",
        "Rahul clicks the urgent link in the email.",
        "He enters his student portal login details on the fake website.",
        "The scammer uses his password to hijack his account and send spam."
      ],
      mistakes: [
        "Rahul did not check the sender's email address closely.",
        "He trusted a direct selection offer that didn't require an interview.",
        "He entered his credentials on a website without checking the URL bar."
      ],
      question: "What was the main warning sign Rahul missed in the email?",
      options: [
        "The email did not have any images.",
        "The email offered a remote job opportunity.",
        "The sender's address was 'hr@majorcompany-internships.com' instead of the official company domain, and he was asked to log in on an external page.",
        "The email was sent during evening hours."
      ],
      correctAnswer: 2,
      explanation: "Lookalike domains (like majorcompany-internships.com) and redirects to external login pages are key phishing indicators. Always check the official website domain in the address bar before logging in.",
      lessonsLearned: [
        "Always check the URL in the address bar before typing passwords.",
        "Official companies rarely offer internships without an interview process.",
        "If a page redirects you to log in, go directly to the official site instead of using the provided link."
      ]
    }
  },
  {
    id: "unit-2",
    title: "Email Security",
    difficulty: "Beginner",
    estimatedTime: "15 min",
    lessons: [
      {
        id: "lesson-2-1",
        title: "Spotting Phishing Clues",
        summary: "Learn to identify fake emails by looking at sender details, urgent threats, and sketchy links.",
        readTime: "4 min read",
        difficulty: "Beginner",
        explanation: "Phishing is when scammers send fake emails that look like they are from trusted companies (like Netflix or Google) to trick you into sharing passwords or card details. You can spot them by checking: 1) Sender address spelling errors, 2) Threatening warnings (e.g. 'Your account will be closed in 24 hours'), and 3) Weird links that don't match the official website.",
        illustration: `+-------------------------------------------------------------+
| ANATOMY OF A PHISHING EMAIL                                 |
|                                                             |
| From: Netflix Billing <support@netflx-payments.com> [FAKE!] |
| Subject: URGENT: Account Suspension                         |
|                                                             |
| Please update card details: http://verify-netflix.net/log   |
|                                     [FAKE LINK!]            |
+-------------------------------------------------------------+`,
        takeaways: [
          "Display names can be faked. Always check the actual email domain after the '@' symbol.",
          "Be highly suspicious of emails that create panic or push you to act quickly.",
          "Hover over links to see where they actually lead before clicking."
        ],
        activity: {
          type: "compare-emails",
          title: "Compare Emails: Real vs Fake",
          instructions: "Compare the two emails below. Inspect the sender address, urgency, links, and grammar. Click on the suspicious parts of the fake email!",
          data: {
            scenario: "paypal"
          }
        },
        quiz: [
          {
            q: "If an email has the logo of your bank but is sent from 'service@bank-security-update.com', is it safe?",
            options: [
              "Yes, because the bank logo is present.",
              "Yes, the domain has the word 'bank' in it.",
              "No, scammers create lookalike domains and copy logos to appear legitimate.",
              "Only if it was sent during business hours."
            ],
            correctAnswer: 2,
            explanation: "Anyone can copy a logo. Bank emails only come from official domains (like @yourbank.com), not lookalikes like bank-security-update.com."
          }
        ]
      },
      {
        id: "lesson-2-2",
        title: "Lookalike Domains (Spoofing)",
        summary: "Understand how scammers use tiny spelling tricks to make fake websites look real.",
        readTime: "3 min read",
        difficulty: "Beginner",
        explanation: "Domain spoofing is a trick where scammers buy web domains that look very similar to popular websites to fool you. They might swap letters (like using a capital 'I' instead of a lowercase 'l', e.g., 'paypaI.com' vs 'paypal.com'), add hyphens, or use different endings like '.net' instead of '.com'. Always look at the address bar carefully.",
        illustration: `+-------------------------------------------------------------+
| LOOKALIKES VS REAL DOMAINS                                  |
|                                                             |
| Real Domain:  paypal.com                                    |
| Fake Domain:  paypaI.com   (Uses a capital 'I' to mimic 'l')|
| Fake Domain:  google-security-update.net                    |
+-------------------------------------------------------------+`,
        takeaways: [
          "Inspect website addresses letter-by-letter.",
          "When in doubt, search for the official website on Google instead of clicking links.",
          "Use a browser that clearly highlights the main website domain."
        ],
        activity: {
          type: "fake-screenshots",
          title: "Spot the Spoofed Domain",
          instructions: "Read the domain names and identify which ones are spoofed (fake) and which ones are official.",
          data: {
            scenario: "domains",
            items: [
              { label: "support@amazon.com", isReal: true, desc: "Official Amazon domain." },
              { label: "refund@amazon-support-desk.net", isReal: false, desc: "Hyphenated lookalike domain." },
              { label: "security@micros0ft.com", isReal: false, desc: "Uses '0' (zero) instead of 'o'." },
              { label: "billing@netflix.com", isReal: true, desc: "Official Netflix domain." }
            ]
          }
        },
        quiz: [
          {
            q: "Which of the following is a spoofed domain?",
            options: [
              "accounts.google.com",
              "google-login-verify.com",
              "mail.google.com",
              "support.google.com"
            ],
            correctAnswer: 1,
            explanation: "Scammers add extra words and hyphens (like google-login-verify.com) to make fake sites look official. Official subdomains are separated only by periods (like accounts.google.com)."
          }
        ]
      },
      {
        id: "lesson-2-3",
        title: "Dangerous Attachments",
        summary: "Learn why downloading files from emails can install silent viruses on your device.",
        readTime: "3 min read",
        difficulty: "Intermediate",
        explanation: "Scammers use email attachments to deliver viruses. When you download and open a file, it can run hidden code that locks your files, logs your keystrokes, or steals passwords. Be careful with double extensions (like 'invoice.pdf.exe') and compressed folders (like '.zip' or '.rar') which hide the real files inside.",
        illustration: `+-------------------------------------------------------------+
| DANGEROUS DOUBLE EXTENSIONS                                 |
|                                                             |
| File Name:  receipt_29381.pdf.exe                           |
| Real Type:  Executable Program (Runs virus immediately!)    |
| Trick:      Hides behind a PDF icon to fool you             |
+-------------------------------------------------------------+`,
        takeaways: [
          "Never download attachments from unknown senders.",
          "Check the file extension: documents are `.pdf` or `.docx`, programs are `.exe` or `.scr`.",
          "Use cloud viewers to preview files without downloading them."
        ],
        activity: {
          type: "permissions-review",
          title: "Attachment Safety Audit",
          instructions: "Audit the list of email attachments. Decide which files are safe to download and which ones are highly dangerous.",
          data: {
            scenario: "attachments",
            options: [
              { id: "pdf", label: "project_notes.pdf", desc: "Standard document. Generally safe but scan first.", rating: "Safe" },
              { id: "exe", label: "invoice_detail.exe", desc: "Program file. Can execute virus code instantly.", rating: "Dangerous" },
              { id: "zip", label: "photos.zip", desc: "Compressed folder. Can hide malicious files.", rating: "Use Caution" }
            ]
          }
        },
        quiz: [
          {
            q: "What type of file extension is most dangerous to open in an email?",
            options: [
              ".pdf",
              ".png",
              ".exe",
              ".docx"
            ],
            correctAnswer: 2,
            explanation: "An `.exe` file is a program. Opening it allows the program to run immediately on your computer, which can install malware."
          }
        ]
      }
    ],
    caseStudy: {
      title: "The Urgent Courier Delivery Trap",
      background: "Ananya was expecting a parcel delivery from an online order.",
      story: "Ananya received a text message saying her package was on hold due to an incorrect home address. The message contained a link to update her details and pay a tiny $1.50 address correction fee. Since she was expecting a package, she clicked the link. The webpage looked exactly like a popular national post office portal. She typed in her home address and her credit card details to pay the small fee. Within an hour, she received alerts from her bank showing that $1,200 had been spent on her card online.",
      timeline: [
        "Ananya orders clothes online.",
        "Scammer sends a mass text message pretending to be a postal courier.",
        "Ananya clicks the link, believing it's for her actual order.",
        "She enters her address and credit card details.",
        "Scammer uses her card details to make unauthorized online purchases."
      ],
      mistakes: [
        "Ananya assumed the message was about her specific order without checking with the retailer.",
        "She paid a fee on a website she reached via a text message link.",
        "She didn't inspect the website URL, which was 'post-office-delivery-fees.net' instead of the official post office portal."
      ],
      question: "Why do scammers ask for very small fees (like $1.50) in courier scams?",
      options: [
        "Because their servers are cheap to run.",
        "To test if the credit card has enough balance.",
        "To make users let their guard down and enter card details without thinking.",
        "Because they are nice scammers."
      ],
      correctAnswer: 2,
      explanation: "Scammers use tiny fees ($1.00 - $3.00) because victims don't think twice about paying small amounts. The scammers don't care about the $1.50; they want to steal the credit card number, expiry date, and CVV code to use later.",
      lessonsLearned: [
        "Official post offices do not send text messages with links asking for correction fees.",
        "Track shipments directly on the retailer's official website, not through SMS links.",
        "If asked for card details for a tiny fee, stop and call the company's verified helpline first."
      ]
    }
  },
  {
    id: "unit-3",
    title: "Safe Payments",
    difficulty: "Intermediate",
    estimatedTime: "20 min",
    lessons: [
      {
        id: "lesson-3-1",
        title: "Understanding UPI & QR Safety",
        summary: "Learn the golden rule of UPI: Scanning a QR code or entering your PIN is ONLY for sending money.",
        readTime: "4 min read",
        difficulty: "Beginner",
        explanation: "UPI and QR codes make payments incredibly simple. However, scammers take advantage of this by sending QR codes and claiming: 'Scan this code to receive your refund/payment.' The absolute rule of UPI is: **You never need to enter your UPI PIN to receive money.** Entering your PIN only approves a transfer *out* of your account.",
        illustration: `+-------------------------------------------------------------+
| THE GOLDEN RULE OF UPI                                      |
|                                                             |
| Entering PIN / Scanning QR   ===>  Sends money OUT          |
| Receiving Money              ===>  Requires NO action       |
|                                                            |
| * If someone asks you to type your PIN to receive money,     |
|   it is 100% a scam!                                        |
+-------------------------------------------------------------+`,
        takeaways: [
          "Scanning a QR code is strictly for making a payment.",
          "Receiving money happens automatically; you never need to type a PIN.",
          "Always read the UPI app screen carefully before tapping 'Pay'."
        ],
        activity: {
          type: "fake-screenshots",
          title: "Identify Fake UPI Requests",
          instructions: "Look at the mock payment screens. Decide if they are safe transaction requests or deceptive scams.",
          data: {
            scenario: "upi",
            items: [
              { label: "Request to PAY: Scammer requests $500 for 'Refund Verification'. PIN required.", isReal: false, desc: "A request to pay, disguised as a refund." },
              { label: "Incoming Transfer: Your friend sent you $50. No action required.", isReal: true, desc: "A standard incoming payment. No PIN needed." },
              { label: "Scan to RECEIVE: 'Scan this QR code to claim your prize!'. App opens payment screen.", isReal: false, desc: "QR codes only send money. Tapping approve will debit your account." }
            ]
          }
        },
        quiz: [
          {
            q: "A buyer on an online marketplace wants to pay you. They send a QR code and tell you to scan it and enter your PIN to receive the cash. What should you do?",
            options: [
              "Scan the code quickly before they change their mind.",
              "Scan it, but enter a wrong PIN first to test it.",
              "Refuse. Scanning a code and entering a PIN always debits your account; you never do this to receive money.",
              "Call your bank to approve the incoming code."
            ],
            correctAnswer: 2,
            explanation: "You never need to scan a code or enter a PIN to receive money. Anyone claiming otherwise is trying to steal funds from your account."
          }
        ]
      },
      {
        id: "lesson-3-2",
        title: "Spotting Fake Payment Screenshots",
        summary: "Identify mock transaction confirmation screens used by scammers to trick shopkeepers.",
        readTime: "3 min read",
        difficulty: "Intermediate",
        explanation: "Some scammers buy items in stores, pretend to pay using UPI, and show a 'Payment Successful' screen on their phone. However, this screen is created by a fake app. They spoof the shopkeeper's name, amount, and date. To protect yourself, never rely on a screenshot. Always wait for the official SMS notification, check your bank balance, or listen for the voice alert from your shop's payment speaker.",
        illustration: `+-------------------------------------------------------------+
| FAKE VS REAL TRANSACTION CHECKS                             |
|                                                             |
| Scammer Phone:  Shows 'Success' Screen   ===> NOT RELIABLE! |
| Shop Speaker:   'Received 100 Rupees'    ===> VERIFIED!     |
| Bank App:       Balance updated          ===> VERIFIED!     |
+-------------------------------------------------------------+`,
        takeaways: [
          "Screenshots shown by customers are easily faked using mock apps.",
          "Wait for the SMS alert or check your official merchant ledger.",
          "Verify the transaction ID directly in your app if in doubt."
        ],
        activity: {
          type: "fake-screenshots",
          title: "Audit Transaction Screenshots",
          instructions: "Look at the details of the transaction confirmation. Spot the errors that give away the fake app screenshot!",
          data: {
            scenario: "screenshots"
          }
        },
        quiz: [
          {
            q: "What is the safest way for a merchant to verify they have received a UPI payment?",
            options: [
              "Looking at the customer's phone screen showing 'Success'.",
              "Taking a photo of the customer's ID.",
              "Checking their own bank app balance, merchant ledger, or waiting for an official payment sound notification.",
              "Asking the customer to write down their transaction number."
            ],
            correctAnswer: 2,
            explanation: "Customer screens are easily spoofed. Only trust notifications on your own device, bank balances, or official speaker boxes."
          }
        ]
      }
    ],
    caseStudy: {
      title: "The OLX QR Code Payment Scam",
      background: "Vikram listed his old bicycle for sale on an online marketplace (OLX) for $120.",
      story: "Within ten minutes of listing, Vikram was contacted by a buyer who agreed to the price immediately without negotiating. The buyer claimed they couldn't come in person but would send their assistant to pick it up, and wanted to pay Vikram in advance via UPI. The buyer sent a QR code on WhatsApp, telling Vikram: 'Scan this QR code in your app to receive the $120 advance payment.' Vikram scanned the code, entered his UPI PIN, and instantly received a notification that $120 was deducted from his account. When he messaged the buyer, they claimed it was an error and sent another QR code to 'refund' the money, which Vikram scanned again, losing another $120.",
      timeline: [
        "Vikram lists a bicycle for sale.",
        "Scammer poses as an eager buyer wanting to pay in advance.",
        "Scammer sends a QR code labeled 'Scan to receive money'.",
        "Vikram scans the code and enters his PIN.",
        "Money is deducted. Scammer blocks Vikram's phone number."
      ],
      mistakes: [
        "Vikram scanned a QR code to receive money.",
        "He typed his private UPI PIN for a transaction that was supposed to credit his account.",
        "He scanned a second code hoping to get a refund for the first mistake."
      ],
      question: "What is the primary rule to remember to avoid QR payment scams?",
      options: [
        "Only scan QR codes in dark rooms.",
        "QR codes are only for sending payments. You never scan a code or enter a PIN to receive money.",
        "Only scan QR codes from verified accounts.",
        "Make sure the QR code has a green border."
      ],
      correctAnswer: 1,
      explanation: "QR codes are links that authorize outgoing payments. Scanning a QR code inside a UPI app will always prepare to send money out, not receive it. A recipient never needs to scan a QR code.",
      lessonsLearned: [
        "Never scan a QR code if you are the seller receiving money.",
        "If you enter your PIN, you are sending money. Period.",
        "Be wary of buyers who buy items immediately without asking questions or inspecting them."
      ]
    }
  },
  {
    id: "unit-4",
    title: "Privacy Posture",
    difficulty: "Intermediate",
    estimatedTime: "15 min",
    lessons: [
      {
        id: "lesson-4-1",
        title: "Managing App Permissions",
        summary: "Check which apps have access to your private data like location, microphone, and files.",
        readTime: "4 min read",
        difficulty: "Beginner",
        explanation: "When you download apps, they often request permission to access parts of your phone, like your location, contacts, camera, or files. Many apps request permissions they don't actually need—for example, a simple flashlight app asking to read your contacts. Scammers write apps that harvest this data to track you or steal your details.",
        illustration: `+-------------------------------------------------------------+
| APP PERMISSION AUDIT EXAMPLE                                |
|                                                             |
| Flashlight App  ===>  Requests Contacts & Location?  ===> DENY |
| Google Maps     ===>  Requests Location?              ===> ALLOW |
|                                                            |
| * Only grant permissions that are necessary for the app!     |
+-------------------------------------------------------------+`,
        takeaways: [
          "Only grant permissions that make sense for the app's function.",
          "Check app permissions regularly in your phone's settings.",
          "Deny permissions for apps you haven't used in a long time."
        ],
        activity: {
          type: "permissions-review",
          title: "Audit App Permissions",
          instructions: "Look at these app permission requests. Decide whether to ALLOW or DENY based on what the app does.",
          data: {
            scenario: "permissions",
            options: [
              { id: "game-contacts", label: "Offline Car Game requests Contacts", desc: "Why does an offline racing game need to read your friends list?", rating: "Deny" },
              { id: "chat-mic", label: "Video Chat App requests Microphone", desc: "Needed to transmit your voice during calls.", rating: "Allow" },
              { id: "weather-location", label: "Weather App requests Background Location", desc: "Wants to track your movement 24/7. Better to set 'Only while using app'.", rating: "Restrict" }
            ]
          }
        },
        quiz: [
          {
            q: "A simple calculator app requests permission to view your calendar and contacts. What should you do?",
            options: [
              "Approve it, since calculator apps are safe.",
              "Deny the permissions, as a calculator has no logical need for your contact list or calendar.",
              "Uninstall the calculator and buy a physical one.",
              "Only approve the calendar permission."
            ],
            correctAnswer: 1,
            explanation: "If an app requests access to sensors or databases that do not match its utility, deny the access. Unnecessary access is often used for advertising tracking or data theft."
          }
        ]
      },
      {
        id: "lesson-4-2",
        title: "Browser Privacy Configurations",
        summary: "Learn how to block tracking scripts, cookie logs, and target advertisements.",
        readTime: "3 min read",
        difficulty: "Intermediate",
        explanation: "Websites load small scripts (called trackers) that follow you around the web to record what you read, search, and buy. They build a profile about you to sell to advertisers. You can protect your privacy by blocking third-party cookies, using private browsing windows, and installing extensions like ad blockers to stop trackers from loading.",
        illustration: `+-------------------------------------------------------------+
| THE TRACKER PIPELINE                                        |
|                                                             |
| You visit Site A ===> Tracker cookie saved to browser        |
| You visit Site B ===> Tracker recognizes cookie, logs habits |
|                                                            |
| Solution: Use private browsing or block third-party cookies!|
+-------------------------------------------------------------+`,
        takeaways: [
          "Block third-party cookies in your browser settings.",
          "Clear your browser cookies and history periodically.",
          "Use a trusted tracker blocker like uBlock Origin."
        ],
        activity: {
          type: "profile-privacy",
          title: "Browser Settings Checklist",
          instructions: "Audit the browser options below and select the settings that offer maximum privacy.",
          data: {
            scenario: "browser"
          }
        },
        quiz: [
          {
            q: "What do third-party cookies do?",
            options: [
              "They save your browser passwords in plain text.",
              "They track your activity across different websites to build an advertising profile about you.",
              "They speed up your downloads.",
              "They protect your device from ransomware."
            ],
            correctAnswer: 1,
            explanation: "Third-party cookies are placed by trackers on sites you visit, tracking your habits across the web."
          }
        ]
      }
    ],
    caseStudy: {
      title: "The Fake KYC Verification Call",
      background: "Pooja received a call from someone claiming to be a customer service representative from her mobile carrier.",
      story: "The caller told Pooja that her SIM card would be deactivated within two hours because her KYC details were outdated. Panicked, Pooja agreed to update her details over the phone. The caller asked her to confirm her address, email, and ID number, which she did. Then, the caller said: 'I am sending a verification code to your phone to confirm your identity. Please read it to me.' Pooja received a code, which actually said 'OTP for Bank Transaction,' but in her hurry, she read the code to the caller. Moments later, Pooja received an alert that her bank account had been cleaned out.",
      timeline: [
        "Pooja receives a call claiming her SIM card is about to be blocked.",
        "The caller creates panic by threatening immediate deactivation.",
        "Pooja shares her personal details (ID, address).",
        "Scammer initiates a bank transfer using her details.",
        "Pooja reads the incoming bank OTP over the phone."
      ],
      mistakes: [
        "Pooja shared her personal details with an unverified caller.",
        "She let panic override her caution.",
        "She read a verification code over the phone without reading the warning text in the SMS."
      ],
      question: "What is the critical mistake Pooja made when she received the verification code?",
      options: [
        "She didn't write it down on paper first.",
        "She did not read the text of the message, which clearly warned that the code was a bank OTP, not a carrier check.",
        "She read the code too slowly.",
        "She hung up the call immediately."
      ],
      correctAnswer: 1,
      explanation: "Verification messages contain warnings (e.g. 'Never share this code with anyone, bank staff will not ask for it'). Always read the full SMS text before using or sharing any code.",
      lessonsLearned: [
        "Mobile carriers and banks will never call and ask you to read back OTP codes.",
        "If someone creates immediate urgency (e.g. 'your card will block in 2 hours'), hang up and call the official support number.",
        "Always read the full text of SMS codes to see what action they are authorizing."
      ]
    }
  },
  {
    id: "unit-5",
    title: "Social Media Safety",
    difficulty: "Beginner",
    estimatedTime: "12 min",
    lessons: [
      {
        id: "lesson-5-1",
        title: "Locking Down Your Profile",
        summary: "Secure your social accounts by hiding private contact details from the public.",
        readTime: "3 min read",
        difficulty: "Beginner",
        explanation: "Social media profiles are goldmines for scammers. By default, profiles are often public, allowing anyone to see your birthday, location, and family members. Scammers use this information to guess security questions, create fake profiles in your name to scam your friends, or build targeted phishing hooks.",
        illustration: `+-------------------------------------------------------------+
| SOCIAL MEDIA ACCOUNT HARVESTING                             |
|                                                             |
| Public Birthday + Mother's Name  ===> Scammer guesses security|
|                                       questions to hack mail!|
|                                                            |
| Action: Lock your profile to 'Friends Only'.                |
+-------------------------------------------------------------+`,
        takeaways: [
          "Change profile visibility to friends-only.",
          "Hide your email, phone number, and birth year from public view.",
          "Don't accept connection requests from strangers."
        ],
        activity: {
          type: "profile-privacy",
          title: "Audit Social Media Privacy Settings",
          instructions: "Toggle the social settings to create a secure, locked profile.",
          data: {
            scenario: "social"
          }
        },
        quiz: [
          {
            q: "Why is it risky to leave your birth year and phone number visible to the public on social media?",
            options: [
              "Your friends will send too many birthday messages.",
              "Scammers can use these details to target you with phone scams or answer security reset questions.",
              "It violates local data copyright laws.",
              "It slows down your social feed updates."
            ],
            correctAnswer: 1,
            explanation: "Public birthdates and phone numbers are key identifiers used by identity thieves and scammers to answer security questions and reset account keys."
          }
        ]
      },
      {
        id: "lesson-5-2",
        title: "Recognizing Data Mining Posts",
        summary: "Learn to spot friendly quizzes and posts designed to steal answers to your security questions.",
        readTime: "3 min read",
        difficulty: "Beginner",
        explanation: "You have probably seen viral quizzes on social media, like 'Find your cartoon name: Your first pet's name + the street you grew up on!' or 'Share your first car!'. While they seem like fun games, these are actually data mining traps. Scammers create them to harvest answers to common password recovery security questions.",
        illustration: `+-------------------------------------------------------------+
| DATA MINING QUIZ TRAP                                       |
|                                                             |
| Viral Post: 'What was your first pet's name? Comment below!'|
| User Comment: 'Snuggles!'                                    |
| Scammer Log:  Hacks account, answers security question:       |
|               'What is your pet's name?' => Snuggles        |
+-------------------------------------------------------------+`,
        takeaways: [
          "Avoid posting in viral comment threads that ask for personal history.",
          "Never share details like your mother's maiden name, first school, or pet names.",
          "When setting security questions, write fake answers that you can remember."
        ],
        activity: {
          type: "fake-screenshots",
          title: "Spot Data Mining Traps",
          instructions: "Identify which social media posts are harmless updates and which ones are designed to mine your security questions.",
          data: {
            scenario: "mining",
            items: [
              { label: "Post: 'Who remembers their first elementary school teacher? Comment below!'", isReal: false, desc: "Data mining post targeting security questions." },
              { label: "Post: 'Look at this beautiful sunset I clicked on my walk today!'", isReal: true, desc: "Harmless personal photo update." },
              { label: "Post: 'Challenge: What city were you born in? First letter of your month + last digit of phone!'", isReal: false, desc: "Data mining post collecting birth city and phone details." }
            ]
          }
        },
        quiz: [
          {
            q: "Why are viral quizzes like 'Your first pet + your mother's maiden name' dangerous?",
            options: [
              "They might install viruses on your phone.",
              "They expose the answers to security questions used by banks and email providers to reset passwords.",
              "They share your GPS location coordinates.",
              "They force you to buy online subscriptions."
            ],
            correctAnswer: 1,
            explanation: "Scammers use these quizzes to collect security question answers from your comments, allowing them to hijack your accounts via 'Forgot Password' flows."
          }
        ]
      }
    ],
    caseStudy: {
      title: "The Instagram Account Theft",
      background: "Kiran, an active social media user, had about 2,000 followers on Instagram.",
      story: "Kiran received a direct message from a friend's profile claiming they were competing in a photography contest and needed his vote. The message said: 'I am sending you a link via SMS. Please copy the link and send it back to me so my vote counts.' Kiran received an SMS with a link, copied it, and sent it back. Within seconds, Kiran was logged out of his Instagram account. The hacker immediately changed his email address, phone number, and password, then posted fake crypto investment schemes to his followers, pretending to be Kiran.",
      timeline: [
        "Kiran gets a direct message from a hacked friend's profile.",
        "Scammer asks Kiran to copy and share an incoming SMS link.",
        "Kiran copies the link and sends it back to the scammer.",
        "The link was a password reset link for Kiran's own account.",
        "Scammer logs Kiran out, takes over the profile, and starts posting scams."
      ],
      mistakes: [
        "Kiran assumed the message was from his real friend without calling them.",
        "He shared an incoming security code link with another user.",
        "He did not read the SMS text, which said 'Instagram password reset link'."
      ],
      question: "What did the SMS link that Kiran copied and shared actually do?",
      options: [
        "It registered a vote in the photography contest.",
        "It gave his phone screen share access.",
        "It was a password reset confirmation link for Kiran's own Instagram profile, letting the scammer bypass verification.",
        "It installed a file scanning script."
      ],
      correctAnswer: 2,
      explanation: "Scammers trigger password resets for their targets and trick them into sharing the reset link or code. Sharing the link allows the scammer to log in and change credentials instantly.",
      lessonsLearned: [
        "Never share password reset links or verification codes sent to your device.",
        "Verify suspicious requests from friends by calling them directly.",
        "Read security messages carefully to see what request they are completing."
      ]
    }
  },
  {
    id: "unit-6",
    title: "Device Security",
    difficulty: "Intermediate",
    estimatedTime: "12 min",
    lessons: [
      {
        id: "lesson-6-1",
        title: "Keeping Systems Updated",
        summary: "Learn how updates patch security vulnerabilities before hackers can exploit them.",
        readTime: "3 min read",
        difficulty: "Beginner",
        explanation: "Operating systems and browsers have errors (called security bugs) that hackers can use to hack into your device without your knowledge. When software developers discover these bugs, they release updates to fix (patch) them. If you skip updates, your phone or computer remains open to attack.",
        illustration: `+-------------------------------------------------------------+
| VULNERABILITY PATCH CYCLE                                   |
|                                                             |
| Bug Found in Browser ===> Hackers attack old browsers!      |
| Update Released      ===> Installer patches security gap    |
|                                                            |
| Action: Turn on auto-updates to stay safe automatically.    |
+-------------------------------------------------------------+`,
        takeaways: [
          "Enable automatic updates for your OS and apps.",
          "Relaunch your browser when prompted to complete updates.",
          "Replace outdated devices that no longer receive security updates."
        ],
        activity: {
          type: "permissions-review",
          title: "Check System Update Status",
          instructions: "Review the system health check and click to apply patches to resolve vulnerabilities.",
          data: {
            scenario: "updates",
            options: [
              { id: "windows-update", label: "Windows OS security update pending (14 days old)", desc: "Fixes zero-day remote execution vulnerability.", rating: "Apply Immediately" },
              { id: "browser-update", label: "Chrome Browser update available (requires restart)", desc: "Patches active exploit in browser sandbox.", rating: "Restart Chrome" },
              { id: "firmware-update", label: "Router Firmware out of date (2 years old)", desc: "Vulnerable to remote DNS hijacking. Needs manual update.", rating: "Update Firmware" }
            ]
          }
        },
        quiz: [
          {
            q: "What is the primary reason software companies release updates?",
            options: [
              "To change the interface layout and confuse users.",
              "To patch security vulnerabilities and fix system bugs.",
              "To delete old files and save server storage.",
              "To track what you search online."
            ],
            correctAnswer: 1,
            explanation: "Updates fix security weaknesses that hackers exploit. Installing updates promptly shuts these entry doors."
          }
        ]
      },
      {
        id: "lesson-6-2",
        title: "Mobile Apps & Store Hygiene",
        summary: "Only download apps from official stores and avoid risky third-party downloads.",
        readTime: "3 min read",
        difficulty: "Beginner",
        explanation: "Official stores (like Google Play or Apple App Store) scan apps for viruses before letting you download them. Third-party websites and forums don't have these checks. Downloading apps from random links (called sideloading) bypasses your phone's security, making it easy for scammers to install spyware.",
        illustration: `+-------------------------------------------------------------+
| APP DOWNLOAD PIPELINE                                       |
|                                                             |
| Official Store ===(Security Scan)===> [Safe App]            |
| Forum Link     ===(No Scan)      ===> [Possible Malware!]   |
+-------------------------------------------------------------+`,
        takeaways: [
          "Never download apps from links in text messages or forums.",
          "Keep 'Sideloading' or 'Unknown Sources' disabled in phone settings.",
          "Check user reviews and download counts before installing any app."
        ],
        activity: {
          type: "permissions-review",
          title: "App Store Audit",
          instructions: "Evaluate the app sources below. Decide if they are safe to install.",
          data: {
            scenario: "sideloading",
            options: [
              { id: "store", label: "Download Whatsapp from Google Play Store", desc: "Verified developer, scanned by Play Protect.", rating: "Safe" },
              { id: "apk", label: "Download 'AdFree Youtube' APK from online forum", desc: "Requires enabling 'Install from Unknown Sources'. No security scan.", rating: "Highly Risky" },
              { id: "link", label: "Click text link to install 'Delivery Tracker' app", desc: "Sent from anonymous mobile number via SMS.", rating: "Dangerous" }
            ]
          }
        },
        quiz: [
          {
            q: "Why is downloading apps from unofficial websites risky?",
            options: [
              "The downloads take too long to complete.",
              "Unofficial sites do not scan apps for spyware, letting scammers bundle viruses inside them.",
              "It is illegal in all countries.",
              "It changes your phone language settings."
            ],
            correctAnswer: 1,
            explanation: "Unofficial files bypass safety audits and often hide malware that steals keystrokes, banking details, or contacts."
          }
        ]
      }
    ],
    caseStudy: {
      title: "The WhatsApp OTP Hijack Scam",
      background: "Mohit was watching television when he received a WhatsApp message from a contact.",
      story: "The message looked like it came from his aunt, saying: 'Mohit, I sent an SMS verification code to your phone by mistake instead of mine. Could you please read it to me quickly? I need it to access my medical portal.' Mohit checked his messages and saw a 6-digit code. Without reading the text, he messaged it back to her. A minute later, Mohit's WhatsApp stopped working. He tried to log back in, but WhatsApp told him he had to wait 12 hours. It turned out his aunt's WhatsApp had been hacked, and the code Mohit sent was the registration code to transfer Mohit's own WhatsApp account to the scammer's phone.",
      timeline: [
        "Aunt's WhatsApp account is hacked by a scammer.",
        "Scammer logs into WhatsApp on a new phone, entering Mohit's number.",
        "WhatsApp sends Mohit a 6-digit registration code via SMS.",
        "Scammer messages Mohit pretending to be his aunt, asking for the code.",
        "Mohit sends the code, and the scammer takes over Mohit's WhatsApp."
      ],
      mistakes: [
        "Mohit shared an SMS registration code.",
        "He trusted the sender's identity without verifying (calling her).",
        "He did not read the SMS text, which said 'WhatsApp Registration Code'."
      ],
      question: "What should you do if a friend or relative messages you asking for a code sent to your phone?",
      options: [
        "Send it immediately to be helpful.",
        "Call them directly to verify if they sent the message, and never share registration codes.",
        "Send a fake code to see what happens.",
        "Ignore the message entirely."
      ],
      correctAnswer: 1,
      explanation: "Scammers use hijacked profiles to target their contacts. If anyone asks you for a code sent to your phone, call them directly to verify. Never share verification codes, especially registration codes.",
      lessonsLearned: [
        "A text message sender's display name or profile image can be faked.",
        "SMS verification codes are personal keys. Never share them with anyone.",
        "If your account is hijacked, notify your contacts via other channels immediately so they don't fall for scams sent from your profile."
      ]
    }
  }
];
